version: 0.2
accounts:
  - name: alice
    coins: ["1000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
  - name: beni
    coins: ["500token"]
  - name: pico
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"

build:
  binary: "Themisd"
