FROM faddat/sos-lite

# Add seeds and such after doing gaia.
# I will prototype the rest of this on gaia.
RUN echo Themis > /etc/hostname && \
		pacman -Syyu --noconfirm docker-compose zerotier-one
#		echo "docker run uprm-inso-4101-2020-2021-s2/Themis" >> /usr/local/bin/firstboot.sh
# TODO: docker-compose
